backend:
  name: git-gateway
  branch: main # or master if that's your default branch
media_folder: static/img # Folder where images will be stored
public_folder: /img
collections:
  - name: blog
    label: Blog
    folder: _posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
